spring:
  application:
    name: playfy
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: playfy
    redis:
      host: ${REDIS_SERVER_HOST}
      port: ${REDIS_SERVER_PORT}
security:
  jwt:
    expiration-time: ${JWT_EXPIRATION_TIME}
    secret-key: ${JWT_SECRET_KEY}
spotify:
  tokenUrl: https://accounts.spotify.com/authorize
  clientId: ${SPOTIFY_CLIENT_ID}
  scope: playlist-read-private playlist-read-collaborative user-library-read
  redirectUri: ${REDIRECT_URI}
  grantTypes:
    accessToken: 'authorization_code'
    refreshToken: 'refresh_token'
  playlistLimit: 20
  playlistGetUrl: /v1/me/playlists?offset={offset}&limit={limit}
  apiDomain: https://api.spotify.com

server:
  port: 8090
#logging:
#  level:
#    root: warn