spring:
  application:
    name: playfy
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: playfy
security:
  jwt:
    expiration-time: ${JWT_EXPIRATION_TIME}
    secret-key: ${JWT_SECRET_KEY}
logging:
  level:
    root: debug